- name: Run docker-compose
  hosts: webservers
  become: true
  collections:
    - community.general
  tasks:
    - name: Install docker and docker-compose
      apt:
        name: ["docker.io", "docker-compose"]
        state: present

    - name: Pull docker images
      docker_compose:
        project_src: ../docker/docker-compose.yml
        pull: yes

    - name: Start docker containers
      docker_compose:
        project_src: ../docker/docker-compose.yml
        up: yes
